apiVersion: apps.have2bfun.com/v1
kind: Application
metadata:
  name: nginx-sample
  namespace: default
  labels:
    app: nginx
spec:
  deployment:
#    replicas: 11
    selector:
      matchLabels:
        app: nginx
    template:
      spec:
        containers:
          - name: nginx
            image: nginx:1.14.0
            ports:
              - containerPort: 80
  service:
    type: NodePort
    ports:
      - port: 80
        targetPort: 80
        nodePort: 30080